Improve overfermentation when retarding a dough
hendricius/the-sourdough-framework pull request #259
Opened 2023-10-24 07:49 UTC by hendricius

This adds retarding to the glossary and adds a note on how the times can be effected when starting with a warmer dough. This fixes #248

2023-10-24 07:50 UTC, hendricius commented on book/troubleshooting/crumb-structures.tex
> -by the bacteria. Furthermore, this style of bread has a significantly lower amount of gluten~\cite{raffaella+di+cagno}
Just saw the line was a bit long and wrapped it.

2023-10-24 10:49 UTC, cedounet requested changes

2023-10-24 10:49 UTC, cedounet commented on book/glossary/glossary.tex
> +\item[\textbf{Retarding:}] The process of slowing down fermentation during the proofing
Please rebase on mine, I fixed several issues with the glossary.

2023-10-25 09:41 UTC, cedounet commented on book/troubleshooting/crumb-structures.tex
> +merely 4 hours if it began at a higher temperature. Thus, it's crucial to
4~hours

2023-10-25 21:09 UTC, hendricius commented
@cedounet thanks! Please have another look.

2023-10-26 07:23 UTC, cedounet commented
Lgtm

2023-10-26 07:23 UTC, cedounet approved these changes

2023-10-26 07:23 UTC, merged