Update Sourdough History
hendricius/the-sourdough-framework pull request #298
Opened 2023-12-04 22:47 UTC by hendricius

This adds another timeline for the sourdough bread history, adds more information and more references.

<img width="927" alt="image" src="https://github.com/hendricius/the-sourdough-framework/assets/816859/dc6c9724-bfae-4829-b50f-ce6dd2d1c310">

2023-12-05 12:00 UTC, hendricius commented
@cedounet thanks ❤️ . What do you think of the additions here overall?

2023-12-05 15:31 UTC, cedounet commented
On Tue, Dec 05, 2023 at 12:01:06PM +0000, Hendrik Kleinwaechter wrote:
> @cedounet thanks ❤️ . What do you think of the additions here overall?

I like it...  but I am somewhat OCD when math do not match :)  Takes me
a while when 10 cm means either 400 years or 12 000 years to be at ease
with it.

That aside it is a nice addition to the book, makes it well rounded
between tips, context and theory.


C/

2023-12-05 20:26 UTC, cedounet requested changes

2023-12-05 20:26 UTC, cedounet commented on book/history/sourdough-history.tex
> +modern bread yeasts, wine yeasts, and beer yeasts~\cite{egypt+beer}
Missing a dot

2023-12-05 20:26 UTC, cedounet commented on book/history/sourdough-history.tex
> +at leaving bread doughs. What would previously take 10~hours
You sure ?

2023-12-07 23:28 UTC, cedounet commented
![image](https://github.com/hendricius/the-sourdough-framework/assets/134267244/637e491a-31a6-4888-a7f7-77a81fa837b8)
Still some work to do but let me know if that is an option.

2023-12-08 11:43 UTC, hendricius commented
@cedounet looks nice. What if you were to use the same read as the background of "Historic breadmaking"?

2023-12-08 12:47 UTC, cedounet commented
On Fri, Dec 08, 2023 at 11:43:22AM +0000, Hendrik Kleinwaechter wrote:
> @cedounet looks nice. What if you were to use the same read as the
> background of "Historic breadmaking"?

I found it a bit too light for text... YMMV as usual.  Will fine tune
then we can discuss.

2023-12-08 17:38 UTC, cedounet commented
Still need to deal with 12000 BC but as is for now
![image](https://github.com/hendricius/the-sourdough-framework/assets/134267244/0dcc78f2-b8d6-4e45-b878-95a20b8df81f)


FYI here is the piknk version:
![image](https://github.com/hendricius/the-sourdough-framework/assets/134267244/79278f6d-8541-45a5-99ab-c7ec14326001)

2023-12-08 18:16 UTC, cedounet commented
Here is the latest, I will push code.
OK latest:
![image](https://github.com/hendricius/the-sourdough-framework/assets/134267244/3466b525-1cdb-45b7-b12b-c08c6a60b2b5)

2023-12-09 15:39 UTC, cedounet approved these changes
LGTM with my changes... if you are OK with it, then hit merge.

2023-12-10 01:23 UTC, hendricius commented
@cedounet thank you! Lovely improvements!

2023-12-10 01:28 UTC, merged